const fs=require('fs'),path=require('path'),vm=require('vm');const root=path.resolve(__dirname,'..');let errors=[];const read=f=>fs.existsSync(path.join(root,f))?fs.readFileSync(path.join(root,f),'utf8'):'';const req=(c,m)=>{if(!c)errors.push(m)};
['style.css','language.js','.nojekyll','README.md','index.html','about.html','research.html','faculty.html','publications.html','collaboration.html','news.html','contact.html','faculty-profile.html','data/faculty.js','data/publications.js'].forEach(f=>req(fs.existsSync(path.join(root,f)),`missing ${f}`));
req(/@media\s*\(/.test(read('style.css')),'missing responsive CSS');req(/\ben\b/.test(read('language.js'))&&/\bzh\b/.test(read('language.js')),'missing bilingual translations');
const pages=['index.html','about.html','research.html','faculty.html','publications.html','collaboration.html','news.html','contact.html'];const nav=['index.html','about.html','research.html','faculty.html','publications.html','collaboration.html','news.html','contact.html'];for(const p of pages){const s=read(p);nav.forEach(h=>req(s.includes(`href="${h}"`),`${p} missing ${h}`));req(s.includes('Advanced Membrane Materials Research Center'),`${p} missing brand`);['FACILITIES','MEMBERS','Professor Profile','Hsieh-Chih Tsai Research Group'].forEach(x=>req(!s.includes(x),`${p} contains legacy ${x}`))}
let ctx={window:{}};vm.createContext(ctx);vm.runInContext(read('data/faculty.js'),ctx);const fac=ctx.window.AMMRC_FACULTY||[];req(fac.length===8,`faculty count ${fac.length}`);req(new Set(fac.map(x=>x.id)).size===8,'faculty ids not unique');['Hsieh-Chih Tsai','Juin-Yih Lai','Wei-Song Hung','(Neal) Tai-Shung Chung','Chien-Chieh Hu','Chih-Chia Cheng','Jem-Kun Chen','Chen-Tsyr Lo'].forEach(n=>req(fac.some(f=>f.nameEn===n),`missing ${n}`));fac.forEach(f=>req(f.photo&&/^images\/faculty\/.+\.(?:jpg|png)$/i.test(f.photo),`missing/invalid photo path for ${f.id}`));
const expectedScopus={'hsieh-chih-tsai':'56187150200','juin-yih-lai':'26643223500','wei-song-hung':'22940523500','tai-shung-chung':'7401571059','chien-chieh-hu':'7404570650','chih-chia-cheng':'24466350300','jem-kun-chen':'7501900889','chen-tsyr-lo':'57199935961'};fac.forEach(f=>req(f.scopusId===expectedScopus[f.id],`bad Scopus ID for ${f.id}`));req(fac.find(f=>f.id==='jem-kun-chen').scopusVerified===false,'Jem-Kun Scopus conflict must remain flagged');
ctx={window:{}};vm.createContext(ctx);vm.runInContext(read('data/publications.js'),ctx);const pubs=ctx.window.AMMRC_PUBLICATIONS||[];req(pubs.length>0,'no publications');req(new Set(pubs.map(p=>p.id)).size===pubs.length,'duplicate publication id');const dois=pubs.filter(p=>p.doi).map(p=>p.doi.toLowerCase());req(new Set(dois).size===dois.length,'duplicate DOI');const ids=new Set(fac.map(f=>f.id));pubs.forEach(p=>{req(p.year>=2022&&p.year<=2026,`bad year ${p.id}`);p.facultyIds.forEach(id=>req(ids.has(id),`unknown faculty ${id}`))});[2022,2023,2024,2025,2026].forEach(y=>req(pubs.some(p=>p.year===y),`no publications for ${y}`));
const pubhtml=read('publications.html');req(pubhtml.indexOf('data/faculty.js')<pubhtml.indexOf('publications.js'),'faculty data must load before publications.js');req(pubhtml.indexOf('data/publications.js')<pubhtml.indexOf('publications.js'),'publication data must load before publications.js');[2022,2023,2024,2025,2026].forEach(y=>req(pubhtml.includes(`#y${y}`),`missing year nav ${y}`));
for(const p of [...pages,'faculty-profile.html']){const s=read(p);for(const m of s.matchAll(/href=\"([^\"#?]+\\.(?:html|css|js))[^\"]*\"/g)){const h=m[1];req(fs.existsSync(path.join(root,h)),`${p} broken local link ${h}`)}}
if(errors.length){console.error('FAIL\n'+errors.join('\n'));process.exit(1)}console.log(`PASS: ${pages.length} core pages, ${fac.length} faculty, ${pubs.length} publications`);
